services:
  app:
    build: .
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      - postgresdb
    env_file: ./.env
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url": "jdbc:postgresql://postgresdb:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DATABASE}",
      "spring.datasource.username": "${POSTGRESDB_USER}",
      "spring.datasource.password": "${POSTGRESDB_ROOT_PASSWORD}",
      "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",
      "spring.jpa.hibernate.ddl-auto": "update"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  postgresdb:
    image: postgres:17
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: "${POSTGRESDB_USER}"
      POSTGRES_PASSWORD: "${POSTGRESDB_ROOT_PASSWORD}"
      POSTGRES_DB: "${POSTGRESDB_DATABASE}"
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - ./pgdata:/var/lib/postgresql

volumes:
  db:
